version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - network
  backend:
    image: ghcr.io/swu-team/backend:latest
    container_name: backend
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./backend/.env.prod
    networks:
      - network
  frontend:
    image: ghcr.io/swu-team/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - network

networks:
  network:
