name: Build and Deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Backend
        working-directory: ./backend
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ghcr.io/swu-team/backend:latest ./backend
          docker push ghcr.io/swu-team/backend:latest

      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ghcr.io/swu-team/frontend:latest ./frontend
          docker push ghcr.io/swu-team/frontend:latest